### PR TITLE
Increase verbosity, fix black-hole startup, try to restore LD_LIBRARY_PATH for startup_script

### PR DESCRIPTION
**Pull request by Sntx626**

### CODE REVIEW

**Comment by technobaboo** [comment]
is this tested and working?

**Comment by Sntx626** [comment]
Well...

I converted it back to a draft.
black-hole seems to be borked: starting it with black-hole causes an animation on interacting with the launcher but closes it immediately.

The logging and env var migration seems to works.
(I set a fake LD_LIBRARY_PATH, since it is not set natively on my machine)

Test by running:
```bash
LD_LIBRARY_PATH=/test nix run --impure
```

**Comment by Sntx626** [comment]
I build it before opening the PR, it did not interact with it much...
My bad.

**Comment by technobaboo** [comment]
i'll be honest... it might just be better to get the newer setup i have working where i have a script and CI manually build the appimage in an appdir then package it up.... wanna talk about it in discord?

**Comment by Sntx626** [comment]
This PR works!

Though "fixing" black-hole makes it hard to impossible to launch the hexagon-launcher in 2d mode. Since you only interact with black hole instead.

**Pull request merged**
